# encoding: UTF-8
$schema_preamble =<<EOSQL
# encoding: UTF-8
#---------------------------------------------------------------------------------
# This file is generated by running the rails-migrater gem. It retrieves the current 
# state of the database, and outputs this schema file.
#
# Note that this schema output definition can be the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.
#---------------------------------------------------------------------------------
EOSQL

$preamble =<<EOSTR

This file will auto generate table schema from the current state of the database. 

Usage: ruby mygr8er.rb -vqlh -s [server] -u [user] -p [password] -d [database]

Defaults: There are default values that can be assigned to the initialize method, which allow you to assign values for the most commonly used options.

Note: This schema.rb definition is an additional source for your database schema, and is useful for migrating existing databases to ActiveRecord style schema, which is database independent. 

You can also use db:schema:load.

It's recommended to check this file into your version control system.

EOSTR


